# Generated by Django 4.1.5 on 2023-02-23 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('distancia', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('estaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='incidencias.estacion')),
            ],
        ),
        migrations.AddField(
            model_name='estacion',
            name='lineas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='incidencias.linea'),
        ),
    ]
