# Generated by Django 4.1.5 on 2023-02-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea',
            name='imagen',
        ),
    ]
