# Generated by Django 4.1.6 on 2023-02-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('foto1', models.ImageField(upload_to='noti')),
                ('foto2', models.ImageField(blank=True, upload_to='noti')),
                ('foto3', models.ImageField(blank=True, upload_to='noti')),
                ('foto4', models.ImageField(blank=True, upload_to='noti')),
                ('foto5', models.ImageField(blank=True, upload_to='noti')),
            ],
        ),
    ]
