# Generated by Django 4.1.5 on 2023-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.CharField(max_length=200)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
