# Generated by Django 4.1.5 on 2023-01-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_ofertas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ofertas',
        ),
    ]
